chore: update README
interledger/web-monetization-extension pull request #188
Opened 2024-03-15 14:08 UTC by raducristianpopa

## Context

Closes #<issue number>.

## Changes proposed in this pull request

2024-03-15 14:10 UTC, raducristianpopa commented
<!-- __WM_EXTENSION_BUILD_PREVIEWS__ -->
<h2>Extension builds preview</h2>

<table role="table">
<thead>
  <tr>
    <th>Name</th>
    <th>Link</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td align="center">Latest commit</td>
    <td align="center">f0f0361404da43c3b0e075a12977d2959eacfed7</td>
  </tr>
  <tr>
    <td align="center">Latest job logs</td>
    <td align="center"><a href="https://github.com/interledger/web-monetization-extension/actions/runs/8297511091">Run #8297511091</a></td>
  </tr>
  <tr><td align="center"><img src="https://img.shields.io/badge/success-3fb950?style=for-the-badge&label=Chrome (493.38KB)" alt="Badge" /></td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/21764055795/artifacts/1329675905">Download</a></td></tr><tr><td align="center"><img src="https://img.shields.io/badge/success-3fb950?style=for-the-badge&label=Firefox (493.36KB)" alt="Badge" /></td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/21764055795/artifacts/1329675914">Download</a></td></tr><tr><td align="center"><img src="https://img.shields.io/badge/success-3fb950?style=for-the-badge&label=Opera (493.26KB)" alt="Badge" /></td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/21764055795/artifacts/1329675917">Download</a></td></tr><tr><td align="center"><img src="https://img.shields.io/badge/success-3fb950?style=for-the-badge&label=Edge (493.26KB)" alt="Badge" /></td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/21764055795/artifacts/1329675909">Download</a></td></tr>
</tbody>
</table>

2024-03-19 10:36 UTC, ionutanin approved these changes

2024-03-19 12:23 UTC, tselit requested changes

2024-03-19 12:23 UTC, tselit commented on README.md
>  Web Monetization is a browser extension that detects Web Monetization on websites using a browser API that allows the
Suggesting rewording: 
The Web Monetization browser extension is an open source implementation of the Web Monetization draft specification - learn more [here](https://webmonetization.org/specification/). The extension is built with React and TypeScript.

This Web Monetization browser extension: 
* Detects whether a user is focused on a website that is Web Monetization enabled. 
* Uses a browser API to create a payment stream from the authorized digital wallet or account of a user, to the website.

2024-03-19 12:47 UTC, huijing commented on README.md
> +<h1 align="center">Web Monetization Extension</h1>
did you want to do `<h1 text-align="center">Web Monetization Extension</h1>`?

2024-03-19 12:47 UTC, huijing commented on README.md
> +</center>
I think we don't need this.

2024-03-19 14:46 UTC, tselit approved these changes

2024-04-03 14:22 UTC, merged