Add intent to background
interledger/web-monetization-extension pull request #307
Opened 2024-06-06 07:27 UTC by dianafulga

#301 
#285

2024-06-06 07:28 UTC, raducristianpopa commented
<!-- __WM_EXTENSION_BUILD_PREVIEWS__ -->
<h2>Extension builds preview</h2>

<table role="table">
<thead>
  <tr>
    <th>Name</th>
    <th>Link</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td align="center">Latest commit</td>
    <td align="center">516185c5aa906b46021e1ca20137298699c62b0c</td>
  </tr>
  <tr>
    <td align="center">Latest job logs</td>
    <td align="center"><a href="https://github.com/interledger/web-monetization-extension/actions/runs/9396833026">Run #9396833026</a></td>
  </tr>
  <tr><td align="center"><img src="https://img.shields.io/badge/success-3fb950?style=for-the-badge&label=Chrome (538.65KB)" alt="Badge" /></td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/24593961183/artifacts/1574087424">Download</a></td></tr><tr><td align="center"><img src="https://img.shields.io/badge/success-3fb950?style=for-the-badge&label=Firefox (538.65KB)" alt="Badge" /></td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/24593961183/artifacts/1574087429">Download</a></td></tr>
</tbody>
</table>

2024-06-06 11:55 UTC, sidvishnoi commented on src/background/services/monetization.ts
> +    const sessionsCount = this.sessions[tabId].size + payload.length
Nit: How about we assign `this.sessions[tabId]` to a variable here first.

2024-06-06 11:55 UTC, sidvishnoi commented on src/background/services/monetization.ts
> +    const sessionsCount = this.sessions[tabId].size + payload.length
Question: shouldn't we exclude `remove` intents from `payload.length` here?
Also, do we emit stopPaymentSession before startPaymentSession so existing sessions get removed first?

2024-06-10 12:16 UTC, sidvishnoi commented on src/background/services/monetization.ts
> +    const sessionsCount = sessions.size + payload.length
Bug: If `sessions` is not set initially, we're not setting it to `new Map()` in the if block. Consider assigning `const sessions` after the if block.

2024-06-10 12:18 UTC, sidvishnoi commented on src/content/services/monetizationTagManager.ts
> +    this.sendStartMonetization(startMonetizationTags)
Question: I think we should `await` the stop and then run the start. I'm worried about race conditions.

2024-06-10 12:19 UTC, sidvishnoi requested changes
A little bug to squash there..

2024-06-11 10:40 UTC, sidvishnoi approved these changes

2024-06-11 12:54 UTC, merged