fix(background): Handle unpeer wallet cases
interledger/web-monetization-extension pull request #465
Opened 2024-07-31 15:37 UTC by dianafulga

#394

2024-07-31 15:38 UTC, raducristianpopa commented
<!-- __WM_EXTENSION_BUILD_PREVIEWS__ -->
<h2>Extension builds preview</h2>

<table role="table">
<thead>
  <tr>
    <th>Name</th>
    <th>Link</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td align="center">Latest commit</td>
    <td align="center">6f618ad81732606402fc13f2dadffc5499116b2d</td>
  </tr>
  <tr>
    <td align="center">Latest job logs</td>
    <td align="center"><a href="https://github.com/interledger/web-monetization-extension/actions/runs/10183296402">Run #10183296402</a></td>
  </tr>
  <tr><td align="center"><img src="https://img.shields.io/badge/success-3fb950?style=for-the-badge&label=Chrome (569.79KB)" alt="Badge" /></td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/26646789178/artifacts/1760824105">Download</a></td></tr><tr><td align="center"><img src="https://img.shields.io/badge/success-3fb950?style=for-the-badge&label=Firefox (569.83KB)" alt="Badge" /></td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/26646789178/artifacts/1760824108">Download</a></td></tr>
</tbody>
</table>

2024-08-02 13:15 UTC, raducristianpopa commented on src/_locales/en/messages.json
> +  },
@RabebOthmani

2024-08-02 13:15 UTC, raducristianpopa commented on src/_locales/en/messages.json
> +    "message": "[TODO] Has invalid links. (UI)"
@RabebOthmani

2024-08-02 13:16 UTC, raducristianpopa commented on src/_locales/en/messages.json
> +    "message": "[TODO] Has invalid links. (UI)"
<img width="442" alt="image" src="https://github.com/user-attachments/assets/b610a671-f438-484b-958c-5799528d380c">

2024-08-02 13:17 UTC, raducristianpopa commented on src/_locales/en/messages.json
> +  },
<img width="440" alt="image" src="https://github.com/user-attachments/assets/3d844fb6-1587-4981-b652-440a66f755f0">

2024-08-05 14:15 UTC, RabebOthmani commented
@raducristianpopa are these still waiting for me?

2024-08-05 14:17 UTC, raducristianpopa commented
> @raducristianpopa are these still waiting for me?

Yes. We added them here as well so you can see where and how they are displayed.

2024-08-05 14:22 UTC, RabebOthmani commented
@raducristianpopa few thoughts before getting into the copy: 
Across the extension, we use payment. Do we want to keep with payments (Unable to process a payment) or use sent money (unable to send money) ? 
Thinking about the average user: will they understand what a peered or unpeered wallets mean? I think it's better to say we can't process the payment, you might need to check with your provider for more details

2024-08-05 14:31 UTC, RabebOthmani commented
For the error message when a website is not monetized, let's go with "This site is not web monetized" (using web monetized on purpose to keep it in the context of web monetization)

2024-08-05 15:13 UTC, raducristianpopa commented
>Across the extension, we use payment. Do we want to keep with payments (Unable to process a payment) or use sent money (unable to send money) ?
Like you mentioned, we are using payment across the extension. Let's stick with this.

>Thinking about the average user: will they understand what a peered or unpeered wallets mean? I think it's better to say we can't process the payment, you might need to check with your provider for more details

No, we should not mention peering for the end user. What I am not sure about is this part: `you might need to check with your provider for more details`. The user doesn't have any details about who the receiver is since we are not showing them the wallet addresses that we found in the page. What is the user going to tell to the support them?

2024-08-05 16:59 UTC, RabebOthmani commented
> No, we should not mention peering for the end user. What I am not sure about is this part: you might need to check with your provider for more details. The user doesn't have any details about who the receiver is since we are not showing them the wallet addresses that we found in the page. What is the user going to tell to the support team for example?

What I'm trying to communicate is the payment failed but that's not the extension's fault. How about : We are unable to process the payment due to issues beyond our control.

2024-08-05 17:15 UTC, RabebOthmani commented
The last one, what do we mean by has invalid linked? Is that when it's a partial problem?

2024-08-06 05:54 UTC, raducristianpopa commented
> The last one, what do we mean by has invalid linked? Is that when it's a partial problem?

The `has invalid links` placeholder that we have, will be displayed to the user when the extension can not send money to the wallet addresses that we're found in the page (in our case, mostly because on the peering). It's not a partial problem. For the partial problem - when we can send to at least one wallet address from the page, we are not going to show the warning.

2024-08-06 11:09 UTC, RabebOthmani commented
We discussed all these scenarios from our perspective. Now that we're working on the message, I'm wondering if from the user's perspective, they are distinct scenarios. The one thing I could think about that would make this last case different (invalid links) is that potentially those links may change in the future. We could say " Currently, we are unable to process payments for this website. This might change in the future should you wish to keep the continuous payment going." What do you think @raducristianpopa

2024-08-06 13:54 UTC, RabebOthmani commented
Final decision per the call: At the moment, you cannot pay this website.

2024-08-07 07:33 UTC, sidvishnoi requested changes
The design looks a bit off at the moment.

<img src="https://github.com/user-attachments/assets/21cae617-7aad-4e4d-87e8-51bdb1005434" width="300">

(And some tiny code changes suggested)

2024-08-07 07:33 UTC, sidvishnoi commented on src/_locales/en/messages.json
> +    "message": "[TODO] We cannot send money (probable cause: un-peered wallets)"
```suggestion
    "message": "At the moment, you cannot pay this website.",
    "description": "We cannot send money (probable cause: un-peered wallets)"
```

2024-08-07 07:33 UTC, sidvishnoi commented on src/_locales/en/messages.json
> +    "message": "[TODO] This website is not monetized."
```suggestion
    "message": "This website is not monetized."
```

2024-08-07 07:33 UTC, sidvishnoi commented on src/popup/pages/Home.tsx
> +      )} */}
Let's remove this for now. Will see when we change UI.
```suggestion
```

2024-08-07 07:33 UTC, sidvishnoi commented on src/popup/pages/Home.tsx
> +  if (hasAllSessionsInvalid) return <AllSessionsInvalid />
Consistency with other conditions.

```suggestion
  if (hasAllSessionsInvalid) {
    return <AllSessionsInvalid />
  }
```

2024-08-07 09:48 UTC, raducristianpopa commented on src/_locales/en/messages.json
> +    "message": "At the moment, you cannot pay this website."
```suggestion
    "message": "At the moment, you can not pay this website."
```

2024-08-07 09:49 UTC, sidvishnoi approved these changes

2024-08-07 09:54 UTC, merged